### ISSUE TITLE
When joining a "Planet Earth" type world, the game crashes.

### ISSUE THREAD

**Issue by earomc** [orangeadam3/terra121#1]
crash log:

```
Time: 2/17/20 5:12 PM
Description: Exception in server tick loop

java.lang.NoSuchFieldError: waterLakeRarity
	at io.github.terra121.EarthTerrainProcessor.<init>(EarthTerrainProcessor.java:88)
	at io.github.terra121.EarthWorldType.createCubeGenerator(EarthWorldType.java:20)
	at net.minecraft.world.WorldProvider.createCubeGenerator(WorldProvider.java:758)
	at net.minecraft.world.WorldServer.initCubicWorldServer(WorldServer.java:1550)
	at io.github.opencubicchunks.cubicchunks.core.CommonEventHandler.onWorldAttachCapabilities(CommonEventHandler.java:121)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_39_CommonEventHandler_onWorldAttachCapabilities_AttachCapabilitiesEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:691)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:679)
	at net.minecraft.world.World.initCapabilities(World.java:3978)
	at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:173)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:122)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:156)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 815648472 bytes (777 MB) / 2113929216 bytes (2016 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID              | Version                    | Source                                          | Signature |
	|:------ |:--------------- |:-------------------------- |:----------------------------------------------- |:--------- |
	| LCHIJA | minecraft       | 1.12.2                     | minecraft.jar                                   | None      |
	| LCHIJA | mcp             | 9.42                       | minecraft.jar                                   | None      |
	| LCHIJA | FML             | 8.0.99.99                  | forge-1.12.2-14.23.5.2847.jar                   | None      |
	| LCHIJA | forge           | 14.23.5.2847               | forge-1.12.2-14.23.5.2847.jar                   | None      |
	| LCHIJA | cubicchunkscore | 1.12.2-0.0.1035.0-SNAPSHOT | minecraft.jar                                   | None      |
	| LCHIJA | cubicchunks     | 1.12.2-0.0.1035.0-SNAPSHOT | CubicChunks-1.12.2-0.0.1035.0-SNAPSHOT-all.jar  | None      |
	| LCHIJA | cubicgen        | 1.12.2-0.0.115.0-SNAPSHOT  | CubicWorldGen-1.12.2-0.0.115.0-SNAPSHOT-all.jar | None      |
	| LCHIJA | malisiscore     | 1.12.2-6.5.1-SNAPSHOT      | malisiscore-1.12.2-6.5.1.jar                    | None      |
	| LCHIJA | terra121        | 0.1                        | terra121-0.1.jar                                | None      |

	Loaded coremods (and transformers): 
CubicGenCoreMod (CubicWorldGen-1.12.2-0.0.115.0-SNAPSHOT-all.jar)
  io.github.opencubicchunks.cubicchunks.cubicgen.asm.coremod.MapGenStrongholdCubicConstructorTransform
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
CubicChunksCoreMod (CubicChunks-1.12.2-0.0.1035.0-SNAPSHOT-all.jar)
  io.github.opencubicchunks.cubicchunks.core.asm.transformer.CubicChunksWorldEditTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	CubicChunks WorldGen Hang Watchdog samples: (no data)
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
[17:12:25] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\morit\AppData\Roaming\minecraftcc\crash-reports\crash-2020-02-17_17.12.24-server.txt

```

**Comment by earomc** [comment]
I built the jar multiple times, I ran setupDecompWorkspace as well and built again but it still crashes.

**Comment by earomc** [comment]
Update: So it seems to work with CubicWorldGen 85, however not with the new 115 version.

**Comment by Barteks2x** [comment]
CubicWorldGen has changed and terra121 needs to be updated to it.

**Comment by orangeadam3** [comment]
I know, im going to try and update tonight. It seems like its only 4 lines.
