### ISSUE TITLE
Terra 121 latest version crashes the server.

### ISSUE THREAD

**Issue by WaxBitz** [orangeadam3/terra121#137]
Hey,
We are a team Nordic - Baltic BTE and I and my team cant get to the server for 1 week. We contacted the server hosters, (we used actually 2 server hoster) and the problem is that terra 121 crashes the server. Please help us. Our team members are panicking.
Crash Report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
CubicChunksCoreMod (CubicChunks-1.12.2-0.0.1055.0-SNAPSHOT-all.jar)
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
CubicGenCoreMod (CubicWorldGen-1.12.2-0.0.126.0-SNAPSHOT-all.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 5/30/20 10:14 AM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
at io.github.terra121.projection.GeographicProjection.orientProjection(GeographicProjection.java:28)
at io.github.terra121.EarthGeneratorSettings.getProjection(EarthGeneratorSettings.java:85)
at io.github.terra121.EarthBiomeProvider.<init>(EarthBiomeProvider.java:39)
at io.github.terra121.EarthWorldType.getBiomeProvider(EarthWorldType.java:29)
at net.minecraft.world.WorldProvider.func_76572_b(WorldProvider.java:58)
at net.minecraft.world.WorldProvider.func_76558_a(WorldProvider.java:40)
at net.minecraft.world.WorldServer.<init>(WorldServer.java:116)
at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:298)
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
-- System Details --
Details:
Minecraft Version: 1.12.2
Operating System: Linux (amd64) version 3.10.0-1062.12.1.el7.x86_64
Java Version: 1.8.0_252, Oracle Corporation
Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 1661586712 bytes (1584 MB) / 2075918336 bytes (1979 MB) up to 2075918336 bytes (1979 MB)
JVM Flags: 4 total; -Xmx2048M -Xms2048M -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP 9.42 Powered by Forge 14.23.5.2847 12 mods loaded, 12 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

| State  | ID                 | Version                    | Source                                            | Signature |
|:------ |:------------------ |:-------------------------- |:------------------------------------------------- |:--------- |
| LCHIJA | minecraft          | 1.12.2                     | minecraft.jar                                     | None      |
| LCHIJA | mcp                | 9.42                       | minecraft.jar                                     | None      |
| LCHIJA | FML                | 8.0.99.99                  | forge1122.jar                                     | None      |
| LCHIJA | forge              | 14.23.5.2847               | forge1122.jar                                     | None      |
| LCHIJA | cubicchunkscore    | 1.12.2-0.0.1055.0-SNAPSHOT | minecraft.jar                                     | None      |
| LCHIJA | cubicchunks        | 1.12.2-0.0.1055.0-SNAPSHOT | CubicChunks-1.12.2-0.0.1055.0-SNAPSHOT-all.jar    | None      |
| LCHIJA | cubicgen           | 1.12.2-0.0.126.0-SNAPSHOT  | CubicWorldGen-1.12.2-0.0.126.0-SNAPSHOT-all.jar   | None      |
| LCHIJA | effortlessbuilding | 1.12.2-2.16                | effortlessbuilding-1.12.2-2.16.jar                | None      |
| LCHIJA | letsencryptcraft   | @VERSION@                  | letsencryptcraft-1.10.2-1.2.0.jar                 | None      |
| LCHIJA | malisiscore        | 1.12.2-6.5.1-SNAPSHOT      | malisiscore-1.12.2-6.5.1.jar                      | None      |
| LCHIJA | terra121           | 0.1                        | terra121-0.1.4.jar                                | None      |
| LCHIJA | worldedit          | 6.1.10-SNAPSHOT            | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None      |

Loaded coremods (and transformers): 
CubicChunksCoreMod (CubicChunks-1.12.2-0.0.1055.0-SNAPSHOT-all.jar)
io.github.opencubicchunks.cubicchunks.core.asm.transformer.CubicChunksWorldEditTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)

CubicGenCoreMod (CubicWorldGen-1.12.2-0.0.126.0-SNAPSHOT-all.jar)
io.github.opencubicchunks.cubicchunks.cubicgen.asm.coremod.MapGenStrongholdCubicConstructorTransform
CubicChunks WorldGen Hang Watchdog samples: (no data)
Profiler Position: N/A (disabled)
Player Count: 0 / 10; []
Is Modded: Definitely; Server brand changed to 'fml,forge'
Type: Dedicated Server (map_server.txt)

**Comment by SmylerMC** [comment]
I am calling EarthGeneratorSettings::getProjection from [my own mod](https://github.com/SmylerMC/terramap) and one of the users is having is client crash with a similar error:

`java.lang.NullPointerException: null
	at io.github.terra121.projection.GeographicProjection.orientProjection(GeographicProjection.java:28) ~[GeographicProjection.class:?]
	at io.github.terra121.EarthGeneratorSettings.getProjection(EarthGeneratorSettings.java:85) ~[EarthGeneratorSettings.class:?]
	at fr.thesmyler.terramap.gui.GuiTiledMap.initGui(GuiTiledMap.java:98) ~[GuiTiledMap.class:?]
	at net.minecraft.client.gui.GuiScreen.setWorldAndResolution(GuiScreen.java:478) ~[blk.class:?]
	at net.minecraft.client.Minecraft.displayGuiScreen(Minecraft.java:1018) ~[bib.class:?]
	at fr.thesmyler.terramap.input.KeyBindings.checkBindings(KeyBindings.java:28) ~[KeyBindings.class:?]
	at fr.thesmyler.terramap.input.KeyBindings.onKeyInput(KeyBindings.java:33) ~[KeyBindings.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_39_KeyBindings_onKeyInput_KeyInputEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.fireKeyInput(FMLCommonHandler.java:565) [FMLCommonHandler.class:?]
	at net.minecraft.client.Minecraft.runTickKeyboard(Minecraft.java:2017) [bib.class:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1808) [bib.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:4442) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]`

I though the error was on my part, but as the error seams to be the same it may come from Terra1:1. The said player is also the only person I know to experience this, and it is consistent.
All my mod does is retrieve the generator's json sent by the server and use it to instantiate a new EarthGeneratorSettings and then gets the projection.

**Comment by SmylerMC** [comment]
I figured out what the problem was in my case: my user was using a old version of Terra1:1 from before the bte projection was added. Guessing from your crash report, it is you case too, so I would suggest you just replace the Terra1:1 jar on your server with the one provided by the new bte installer.

It would be nice if the Github and CurseForge downloads were up to date for people trying install the bte modpack by themselves or in such cases where you only need to update Terra1:1.

Also the fact that the version number is not incremented when such features are added makes it impossible for mods depending on Terram1:1 like mine to check compatibility, it would be really nice if we had a simpler way to identify the version than by matching line numbers on crash reports with the git commit history.

**Comment by orangeadam3** [comment]
Yeah, thanks @SmylerMC, the jar seems to be out of date. Get the version from https://jenkins.altillimity.com/job/Terra/ for anything BTE related.
GeographicProjection.java:28 no longer even points to a function, in the current version it points to some white space between functions, so the version must be out of date. 
We were looking into some clean solutions to automatic version incrementing, but so far not much has come of it.
