### ISSUE TITLE
Crashing, upon world loading

### ISSUE THREAD

**Issue by VFCTyrant** [orangeadam3/terra121#60]
Not sure exactly what went wong, it's 2:30am here, I'm tired, I've been troubleshooting this with my non-existent tech skill for about 2 hours now..   went through previous threads here, and got to this point.

Previously I was able to load world types other than Terra1:1, but I was unable to here, no typical minecraft generation would work (even when cubicchunks was off sadly)   I'm not sure if I'm outdated somewhere or what I'm doing wrong. 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CubicChunksCoreMod (CubicChunks-1.12.2-0.0.1055.0-SNAPSHOT-all.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  CubicGenCoreMod (CubicWorldGen-1.12.2-0.0.126.0-SNAPSHOT-all.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 3/31/20 2:39 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.world.World.getSkyColorBody(World.java:1484)
	at net.minecraft.world.WorldProvider.getSkyColor(WorldProvider.java:463)
	at net.minecraft.world.World.func_72833_a(World.java:1475)
	at net.minecraft.client.renderer.EntityRenderer.func_78466_h(EntityRenderer.java:1723)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1273)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.world.World.getSkyColorBody(World.java:1484)
	at net.minecraft.world.WorldProvider.getSkyColor(WorldProvider.java:463)
	at net.minecraft.world.World.func_72833_a(World.java:1475)
	at net.minecraft.client.renderer.EntityRenderer.func_78466_h(EntityRenderer.java:1723)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1273)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)

-- Affected level --
Details:
	Level name: MpServer
	All players: 0 total; []
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 11 - EarthCubic, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 0 total; []
	Retry entities: 0 total; []
	Server brand: ~~ERROR~~ NullPointerException: null
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 399419456 bytes (380 MB) / 1038024704 bytes (989 MB) up to 1427243008 bytes (1361 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx1408m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID              | Version                    | Source                                          | Signature                                |
	|:--------- |:--------------- |:-------------------------- |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft       | 1.12.2                     | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | mcp             | 9.42                       | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | FML             | 8.0.99.99                  | forge-1.12.2-14.23.5.2768-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge           | 14.23.5.2768               | forge-1.12.2-14.23.5.2768-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | cubicchunkscore | 1.12.2-0.0.1055.0-SNAPSHOT | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | cubicchunks     | 1.12.2-0.0.1055.0-SNAPSHOT | CubicChunks-1.12.2-0.0.1055.0-SNAPSHOT-all.jar  | None                                     |
	| UCHIJAAAA | cubicgen        | 1.12.2-0.0.126.0-SNAPSHOT  | CubicWorldGen-1.12.2-0.0.126.0-SNAPSHOT-all.jar | None                                     |
	| UCHIJAAAA | malisiscore     | 1.12.2-6.5.1-SNAPSHOT      | malisiscore-1.12.2-6.5.1.jar                    | None                                     |
	| UCHIJAAAA | terra121        | 0.1                        | terra121-0.1.4.jar                              | None                                     |

	Loaded coremods (and transformers): 
CubicChunksCoreMod (CubicChunks-1.12.2-0.0.1055.0-SNAPSHOT-all.jar)
  io.github.opencubicchunks.cubicchunks.core.asm.transformer.CubicChunksWorldEditTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
CubicGenCoreMod (CubicWorldGen-1.12.2-0.0.126.0-SNAPSHOT-all.jar)
  io.github.opencubicchunks.cubicchunks.cubicgen.asm.coremod.MapGenStrongholdCubicConstructorTransform
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13571 Compatibility Profile Context 19.9.2 26.20.13003.1007' Renderer: 'Radeon RX 580 Series'
	CubicChunks WorldGen Hang Watchdog samples: (no data)
	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: Radeon RX 580 Series GL version 4.6.13571 Compatibility Profile Context 19.9.2 26.20.13003.1007, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 1600 Six-Core Processor

**Comment by VFCTyrant** [comment]
Update: Upon waking up, removed the terra 1:1 mod and attempted to launch
ran into a memory error, tweaked around a bit, got it to work on all terrain generation types.

Added terra 1:1 back: world properly loaded on default setting (with cubicchunks enabled)
On to Planet Earth, I have successfully loaded, not sure exactly what my problem was, but it seems to be fixed.
